print(f"😎 " * 6)
l = "  " * 5
print(f"😎 " + l + "  😎")
print(f"😎 " + l + "  😎")
print(f"😎 " + l + "  😎")
print(f"😎 " + l + "  😎")
print(f"😎 " + l + "  😎")
print(f"😎 " + l + "  😎")
print(f"😎 " + l + "  😎")
print(f"😎 " + l + "  😎")
print(f"😎 " + l + "  😎")
print(f"😎 " + l + "  😎")
print(f"😎 " + l + "  😎")
print(f"😎 " * 6)
